### ISSUE TITLE
能否添加标记5个特征点的代码？Can you add code to remark five marker?

### ISSUE THREAD

**Issue by jaysimon** [Longqi-S/ncnn-mtcnn#1]
在源代码中未找到，程序运行了一下，速度喜人，不过因为不太熟悉，所有想知道怎么画出示例中5个标记点
The speed is fast on my vmware ubuntu, but I didnt find code for remark such as eyes and mouth, could you add code?

**Comment by jaysimon** [comment]
已经找到了，struct Bbox结构中的ppoint就是，想办法搞出来就行了。

**Comment by Longqi-S** [comment]
@jaysimon Hello, you can use "for(int num = 0; num < 5; num++) circle(img, points[i], points[i+5], 3, Scalar(0,255,255), -1);" to show 5 points; Where points is the ppoint in Bbox structure;

**Comment by jaysimon** [comment]
thanks a lot @Longqi-S

**Comment by jaysimon** [comment]
@Longqi-S could you send me the .caffemodel and prototxt？
Please，I need to compare ncnn and caffe cpp result
houwei9098@163.com

**Comment by jaysimon** [comment]
@Longqi-S could you send me the .caffemodel and .prototxt？
Please， I need to compare the performance between pc and arm.
thx a lot
monkey1510@gmail.com

**Comment by Longqi-S** [comment]
@jaysimon orginal model files are here;
[mtcnn.zip](https://github.com/Longqi-S/ncnn-mtcnn/files/1584733/mtcnn.zip)

**Comment by jaysimon** [comment]
@Longqi-S Thanks for your help!
It seems that your model is from https://github.com/moli232777144/mtcnn_ncnn.
I transform the **det1.caffemodel** to ncnn **det1_jaysimon.bin**, and I found the param between yours **det1_longqi-S.bin** and **det1_jaysimon.bin** is in a different order. It confuse me.
For example :
The transformed **det1_jaysimon.bin** conv1 order is 
0 1 2 3 4 5 6 7 8 
Your **det1_longqi-S.bin** conv1 order is 
0 3 6 1 4 7 2 5 8

However, I changed the params order the same as yours, and I used the caffe cpp API to compute ,then I got the right answer.

**Comment by Longqi-S** [comment]
@jaysimon the model files is the original files from caffe repository. Btw, ncnn model is col-major, we need row-major model. Thus, you need change the order or modify the ncnn model generation rules.

**Comment by jaysimon** [comment]
@Longqi-S I wonder in which step you changed the order? Using caffe or ncnn?

**Comment by Longqi-S** [comment]
@jaysimon in the stage of  transforming the model using ncnn;
