### ISSUE TITLE
Instruction to make 

### ISSUE THREAD

**Issue by wjtan99** [Longqi-S/ncnn-mtcnn#3]
Hi, I replaced the directory mtcnn of https://github.com/ElegantGod/ncnn with your repo.  However, it could not compile.  The first error is net.h cannot be found.  I tried comment this file, then there were more errors.  
Can you give some instructions how I should I compile it?  
Thanks.

**Comment by Longqi-S** [comment]
@wjtan99 1. Compile the original https://github.com/ElegantGod/ncnn and get include and lib;  2. Using my CMakeLists.txt  to compile mtcnn in this repository;

**Comment by wjtan99** [comment]
Do you have an idea what the following errors are: 

/home/ubuntu/opensource/MTCNN/ElegantGod-ncnn/mtcnn-Shilong/MTCNN.cpp: In function ‘int main(int, char**)’:
/home/ubuntu/opensource/MTCNN/ElegantGod-ncnn/mtcnn-Shilong/MTCNN.cpp:293:5: error: in C++98 ‘model_file’ must be initialized by constructor, not by ‘{...}’
     };
     ^
/home/ubuntu/opensource/MTCNN/ElegantGod-ncnn/mtcnn-Shilong/MTCNN.cpp:293:5: error: could not convert ‘{"../models/det1.param", "../models/det2.param", "../models/det3.param"}’ from ‘<brace-enclosed initializer list>’ to ‘std::vector<std::basic_string<char> >’
/home/ubuntu/opensource/MTCNN/ElegantGod-ncnn/mtcnn-Shilong/MTCNN.cpp:299:5: error: in C++98 ‘trained_file’ must be initialized by constructor, not by ‘{...}’
     };
     ^
/home/ubuntu/opensource/MTCNN/ElegantGod-ncnn/mtcnn-Shilong/MTCNN.cpp:299:5: error: could not convert ‘{"../models/det1.bin", "../models/det2.bin", "../models/det3.bin"}’ from ‘<brace-enclosed initializer list>’ to ‘std::vector<std::basic_string<char> >’
make[2]: *** [CMakeFiles/mtcnn.dir/MTCNN.cpp.o] Error 1
make[1]: *** [CMakeFiles/mtcnn.dir/all] Error 2
make: *** [all] Error 2

Thanks a lot.

**Comment by Longqi-S** [comment]
@wjtan99 Maybe, you can try C++ 11.

**Comment by wjtan99** [comment]
Problem solved.  Have to use C++11 on your code AND the https://github.com/ElegantGod/ncnn.  The ElegantGod does not use C++11 in his CMakeLists.txt. 
Thanks.
