### ISSUE TITLE
你好，arm上的速度如何呢

### ISSUE THREAD

**Issue by liuqunzhong** [Longqi-S/ncnn-mtcnn#4]
大佬好，在arm上测试性能如何呢
arm型号，图像大小，最小人脸，人脸个数等

**Comment by Longqi-S** [comment]
@liuqunzhong Hello, I have tested it in Android OS based on armeabi-v7a reaching 15-20fps; I cannot remember detailed parameters . You can test it by yourself. I think  you can get a better result.
