### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by Josuercuevas** [Longqi-S/ncnn-mtcnn#6]
Hi there @Longqi-S, there is a problem when I try to compile this code, the error is described below:

/MTCNN.cpp:130:20: error: no match for ‘operator=’ (operand types are ‘std::multimap<float, int>::iterator {aka std::_Rb_tree_iterator<std::pair<const float, int> >}’ and ‘void’)
                 it = vScores.erase(it);

as for my CMakeList.txt I did not modify it, please advise  as to what this problem could be.

**Comment by HansRen1024** [comment]
hi bro, did you solve this error?

**Comment by Josuercuevas** [comment]
@HandsomeHans 

Yes it was just my version of gcc, I am using 5.4.0 and it is fine now. I forgot about this issue sorry I did not post it here. I guess we can close this issue now.

**Comment by Longqi-S** [comment]
@Josuercuevas Thanks

**Comment by HansRen1024** [comment]
@Josuercuevas Thanks for your reply. However, my version of gcc is 5.4.0
`Linux hans-PowerEdge-T630 4.4.0-128-generic #154-Ubuntu SMP Fri May 25 14:15:18 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
`

`gcc (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
`
