### ISSUE TITLE
编译的时候说没有net.h文件

### ISSUE THREAD

**Issue by Andrawzyf** [Longqi-S/ncnn-mtcnn#8]
如标题。。

**Comment by immarioo** [comment]
你把ncnn编译好后会在build下生成一个include和lib文件，需要把这个加上放在路径下，然后在CMakeists.txt中指定include和lib的路径。

**Comment by Andrawzyf** [comment]
> 你把ncnn编译好后会在build下生成一个include和lib文件，需要把这个加上放在路径下，然后在CMakeists.txt中指定include和lib的路径。

好的，谢谢~
